### ISSUE TITLE
'configure' error

### ISSUE THREAD

**Issue by pramesh-cfh11** [ViennaRNA/RNAblueprint#1]
Hello,
I am trying to install this software and getting the following error:

<img width="930" alt="Screen Shot 2019-10-28 at 11 23 22" src="https://user-images.githubusercontent.com/8771757/67691671-5d1a3800-f975-11e9-9994-e8080e9f8321.png">

I am not well-versed in C++, but perhaps the configure file should be checking for prerequisites to adjacency_list.hpp instead of doing an explicit pre-processor check on it? I'd appreciate your help with this issue. Thanks!

**Comment by svenderheld** [comment]
Hi,

We are looking into your issue. Two short questions: On which operating system do you work? Did you install boost-development packages? 

Cheers,
Sven
